Repository XiaoMi/hiui, pull requests merged in 2024-12, with the labels that each got.

#3063 fix(locale-context): 修改英文前往(#3062)
  .changeset/lazy-tools-admire.md
  packages/ui/locale-context/src/locale/en-US.ts
Labels: PR: Bug fix 🔧, comp:pagination, 4.x

#3064 chore: 修改changesets变更记录文件
  .changeset/little-rabbits-change.md
  .changeset/neat-crabs-buy.md
  packages/ui/portal-context/package.json
Labels: 4.x

#3065 chore(core): update deps
  packages/core/core/package.json
Labels: dependencies, 4.x

#3067 chore(portal-context): add deps
  packages/ui/portal-context/package.json
Labels: dependencies, 4.x

#3068 Revert "Release"
  .changeset/lazy-tools-admire.md
  .changeset/little-rabbits-change.md
  .changeset/neat-crabs-buy.md
  .changeset/selfish-seas-impress.md
  packages/core/core/CHANGELOG.md
  packages/core/core/package.json
  packages/ui/date-picker/CHANGELOG.md
  packages/ui/date-picker/package.json
  packages/ui/drawer/CHANGELOG.md
  packages/ui/drawer/package.json
  packages/ui/hiui/CHANGELOG.md
  packages/ui/hiui/package.json
  packages/ui/loading/CHANGELOG.md
  packages/ui/loading/package.json
  packages/ui/locale-context/CHANGELOG.md
  packages/ui/locale-context/package.json
  packages/ui/modal/CHANGELOG.md
  packages/ui/modal/package.json
  packages/ui/picker/CHANGELOG.md
  packages/ui/picker/package.json
  packages/ui/portal-context/CHANGELOG.md
  packages/ui/portal-context/package.json
  packages/ui/preview/CHANGELOG.md
  packages/ui/preview/package.json
  packages/ui/provider/CHANGELOG.md
  packages/ui/provider/package.json
Labels: 4.x

#3070 chore(hiui): add portal-context package
  .changeset/forty-pumpkins-begin.md
  packages/ui/hiui/src/index.ts
Labels: 4.x

#3072 chore(provider): 优化示例
  .changeset/strong-dodos-provide.md
  packages/ui/locale-context/src/index.ts
  packages/ui/provider/stories/basic.stories.tsx
  packages/ui/provider/stories/index.stories.tsx
  packages/ui/provider/stories/portal.stories.tsx
Labels: 4.x, comp:provider

#3074 chore(provider): 修改示例
  packages/ui/provider/stories/portal.stories.tsx
Labels: 4.x, comp:provider
